// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ImmutableHashCollections")>]
[<assembly: AssemblyProductAttribute("ImmutableHashCollections")>]
[<assembly: AssemblyDescriptionAttribute("immutable hash collections benchmarks")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ImmutableHashCollections"
    let [<Literal>] AssemblyProduct = "ImmutableHashCollections"
    let [<Literal>] AssemblyDescription = "immutable hash collections benchmarks"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
